# Generated by Django 4.2.6 on 2023-10-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default='2023-10-18 03:59:40.147440'),
            preserve_default=False,
        ),
    ]
